### ISSUE TITLE
Missing user apps

### ISSUE THREAD

**Issue by poegl** [billyjacoby/browsernaut#24]
Please also consider ~/Applications, currently just /Applications are considered.

**Comment by billyjacoby** [comment]
Should be fixed in v1.1.3 - fix is here: https://github.com/billyjacoby/browsernaut/commit/2fd9a5c572d3d1a96c3247bff1c4ef6d8cbd4c0d

**Comment by billyjacoby** [comment]
@poegl If you could confirm the latest version fixes this I'd appreciate it!

**Comment by poegl** [comment]
Hi, unfortunately not, because Typescript do not expand the tilde character.
I provided a merge request, where the apps are searched through a Rust-function and used in Typescript.
https://github.com/billyjacoby/browsernaut/pull/27
